packageExtensions:
  "@monorepolint/cli@*":
    dependencies:
      tslib: "*"
  "@monorepolint/core@*":
    dependencies:
      "@monorepolint/rules": "^0.5.0-alpha.0"
  "@monorepolint/rules@*":
    dependencies:
      tslib: "*"
  "@monorepolint/utils@*":
    dependencies:
      tslib: "*"
  "@storybook/components@*":
    peerDependencies:
      regenerator-runtime: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
