name: CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn chromatic --exit-once-uploaded --exit-zero-on-changes
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          STORYBOOK_BUILD_TIMEOUT: 1200000 # 20 minutes

  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - run: yarn install --immutable
      - run: yarn fmt:check
      - run: yarn mrl check
