name: CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: echo "::set-output name=dir::$(yarn cache dir)"
        id: yarn-cache-dir-path
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1-
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn chromatic --exit-once-uploaded --exit-zero-on-changes
        if: github.actor != 'dependabot[bot]'
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          STORYBOOK_BUILD_TIMEOUT: 1200000 # 20 minutes

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo "::set-output name=dir::$(yarn cache dir)"
        id: yarn-cache-dir-path
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1-
      - run: yarn install --frozen-lockfile
      - run: yarn fmt:check
      - run: yarn mrl check
