name: CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile
          mkdir -p ~/bin
          curl -L https://github.com/RazrFalcon/svgcleaner/releases/download/v0.9.5/svgcleaner_linux_x86_64_0.9.5.tar.gz | tar zxv -C ~/bin
          chmod +x ~/bin/svgcleaner
          echo "::add-path::$HOME/bin"

      - name: Build
        run: yarn build

      - name: Visual Tests
        run: yarn chromatic --exit-zero-on-changes
        env:
          CHROMATIC_APP_CODE: '${{ secrets.CHROMATIC_APP_CODE }}'
