name: CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CHROMATIC_APP_CODE: '${{ secrets.CHROMATIC_APP_CODE }}'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn chromatic --exit-zero-on-changes
      - uses: changesets/action@master
        if: github.ref == 'refs/heads/main'
        with:
          publish: yarn changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
