name: Release
on: push

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.repository == 'svg-icons/svg-icons'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
        id: yarn-cache-dir-path
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v2-
      - run: yarn install --immutable
      - uses: changesets/action@master
        if: github.ref == 'refs/heads/main' && github.repository == 'svg-icons/svg-icons'
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          GITHUB_USERNAME: icon-bot
          GITHUB_EMAIL: ${{ secrets.BOT_GITHUB_EMAIL }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
